// plantData.js
export const plantData = {
  'sweet potato': { startIndoors: { week: 1, month: 'March' }, transplant: { week: 3, month: 'May' }, harvest: { week: 3, month: 'July' }, spacing: 2 },
  'beets': { sow: { week: 2, month: 'April' }, harvest: { week: 2, month: 'June' }, spacing: 0.25 },
  'carrots': { sow: { week: 2, month: 'April' }, harvest: { week: 4, month: 'June' }, spacing: 0.1 },
  'potatoes': { sow: { week: 4, month: 'March' }, harvest: { week: 1, month: 'July' }, spacing: 1 },
  'radishes': { sow: { week: 1, month: 'April' }, harvest: { week: 4, month: 'April' }, spacing: 0.05 },
  'parsnips': { sow: { week: 3, month: 'April' }, harvest: { week: 2, month: 'October' }, spacing: 0.25 },
  'turnips': { sow: { week: 2, month: 'April' }, harvest: { week: 1, month: 'June' }, spacing: 0.2 },
  'rutabaga': { sow: { week: 1, month: 'July' }, harvest: { week: 4, month: 'October' }, spacing: 0.5 },
  'onions': { startIndoors: { week: 1, month: 'February' }, transplant: { week: 2, month: 'April' }, harvest: { week: 1, month: 'July' }, spacing: 0.25 },
  'garlic': { sow: { week: 3, month: 'October' }, harvest: { week: 2, month: 'June' }, spacing: 0.25 },
  'leeks': { startIndoors: { week: 1, month: 'March' }, transplant: { week: 1, month: 'May' }, harvest: { week: 3, month: 'August' }, spacing: 0.5 },
  'spinach': { sow: { week: 1, month: 'March' }, harvest: { week: 3, month: 'May' }, spacing: 0.2 },
  'lettuce': { sow: { week: 2, month: 'March' }, harvest: { week: 1, month: 'May' }, spacing: 0.25 },
  'kale': { sow: { week: 3, month: 'March' }, harvest: { week: 4, month: 'June' }, spacing: 1 },
  'swiss chard': { sow: { week: 2, month: 'April' }, harvest: { week: 3, month: 'June' }, spacing: 0.5 },
  'arugula': { sow: { week: 2, month: 'March' }, harvest: { week: 4, month: 'April' }, spacing: 0.1 },
  'mustard greens': { sow: { week: 3, month: 'March' }, harvest: { week: 2, month: 'May' }, spacing: 0.25 },
  'collards': { sow: { week: 1, month: 'April' }, harvest: { week: 3, month: 'June' }, spacing: 1 },
  'tomatoes': { startIndoors: { week: 1, month: 'March' }, transplant: { week: 2, month: 'May' }, harvest: { week: 2, month: 'July' }, spacing: 2 },
  'peppers': { startIndoors: { week: 1, month: 'March' }, transplant: { week: 2, month: 'May' }, harvest: { week: 3, month: 'July' }, spacing: 1.5 },
  'zucchini': { sow: { week: 3, month: 'May' }, harvest: { week: 1, month: 'July' }, spacing: 4 },
  'cucumbers': { sow: { week: 3, month: 'May' }, harvest: { week: 4, month: 'June' }, spacing: 2 },
  'eggplant': { startIndoors: { week: 1, month: 'March' }, transplant: { week: 2, month: 'May' }, harvest: { week: 4, month: 'July' }, spacing: 2 },
  'squash': { sow: { week: 3, month: 'May' }, harvest: { week: 2, month: 'July' }, spacing: 4 },
  'pumpkin': { sow: { week: 3, month: 'May' }, harvest: { week: 3, month: 'September' }, spacing: 8 },
  'watermelon': { sow: { week: 1, month: 'May' }, harvest: { week: 1, month: 'August' }, spacing: 6 },
  'cantaloupe': { sow: { week: 1, month: 'May' }, harvest: { week: 4, month: 'July' }, spacing: 4 },
  'okra': { sow: { week: 2, month: 'May' }, harvest: { week: 2, month: 'July' }, spacing: 1.5 },
  'broccoli': { startIndoors: { week: 1, month: 'March' }, transplant: { week: 3, month: 'April' }, harvest: { week: 2, month: 'June' }, spacing: 1.5 },
  'cauliflower': { startIndoors: { week: 1, month: 'March' }, transplant: { week: 3, month: 'April' }, harvest: { week: 3, month: 'June' }, spacing: 2 },
  'cabbage': { startIndoors: { week: 1, month: 'March' }, transplant: { week: 2, month: 'April' }, harvest: { week: 1, month: 'June' }, spacing: 1.5 },
  'brussels sprouts': { startIndoors: { week: 1, month: 'April' }, transplant: { week: 2, month: 'June' }, harvest: { week: 2, month: 'October' }, spacing: 2 },
  'kohlrabi': { sow: { week: 2, month: 'April' }, harvest: { week: 1, month: 'June' }, spacing: 0.25 },
  'beans': { sow: { week: 1, month: 'May' }, harvest: { week: 3, month: 'July' }, spacing: 0.25 },
  'peas': { sow: { week: 1, month: 'March' }, harvest: { week: 2, month: 'May' }, spacing: 0.1 },
  'lima beans': { sow: { week: 2, month: 'May' }, harvest: { week: 4, month: 'July' }, spacing: 0.5 },
  'fava beans': { sow: { week: 1, month: 'March' }, harvest: { week: 3, month: 'May' }, spacing: 0.5 },
  'basil': { startIndoors: { week: 2, month: 'April' }, transplant: { week: 1, month: 'June' }, harvest: { week: 3, month: 'July' }, spacing: 0.5 },
  'dill': { sow: { week: 2, month: 'April' }, harvest: { week: 2, month: 'June' }, spacing: 0.25 },
  'thyme': { startIndoors: { week: 1, month: 'March' }, transplant: { week: 4, month: 'May' }, harvest: { week: 2, month: 'July' }, spacing: 0.5 },
  'oregano': { startIndoors: { week: 1, month: 'March' }, transplant: { week: 4, month: 'May' }, harvest: { week: 3, month: 'July' }, spacing: 0.75 },
  'parsley': { sow: { week: 2, month: 'April' }, harvest: { week: 1, month: 'June' }, spacing: 0.25 },
  'cilantro': { sow: { week: 3, month: 'April' }, harvest: { week: 2, month: 'June' }, spacing: 0.2 },
  'mint': { startIndoors: { week: 1, month: 'March' }, transplant: { week: 3, month: 'May' }, harvest: { week: 1, month: 'July' }, spacing: 1 },
  'rosemary': { startIndoors: { week: 1, month: 'March' }, transplant: { week: 4, month: 'May' }, harvest: { week: 3, month: 'July' }, spacing: 1.5 },
  'sage': { startIndoors: { week: 1, month: 'March' }, transplant: { week: 4, month: 'May' }, harvest: { week: 2, month: 'July' }, spacing: 1 },
  'chives': { sow: { week: 2, month: 'April' }, harvest: { week: 1, month: 'June' }, spacing: 0.25 },
  'strawberries': { startIndoors: { week: 1, month: 'February' }, transplant: { week: 2, month: 'April' }, harvest: { week: 2, month: 'June' }, spacing: 1 },
  'raspberries': { sow: { week: 3, month: 'March' }, harvest: { week: 2, month: 'July' }, spacing: 2 },
  'blackberries': { sow: { week: 3, month: 'March' }, harvest: { week: 3, month: 'July' }, spacing: 3 },
  'blueberries': { sow: { week: 3, month: 'March' }, harvest: { week: 1, month: 'July' }, spacing: 4 },
  'marigolds': { sow: { week: 1, month: 'May' }, harvest: { week: 1, month: 'July' }, spacing: 0.5 },
  'nasturtiums': { sow: { week: 2, month: 'May' }, harvest: { week: 4, month: 'June' }, spacing: 1 },
  'sunflowers': { sow: { week: 2, month: 'May' }, harvest: { week: 2, month: 'August' }, spacing: 2 },
  'zinnias': { sow: { week: 1, month: 'May' }, harvest: { week: 3, month: 'July' }, spacing: 0.75 },
  'cosmos': { sow: { week: 2, month: 'May' }, harvest: { week: 4, month: 'June' }, spacing: 1 },
  'calendula': { sow: { week: 3, month: 'April' }, harvest: { week: 2, month: 'June' }, spacing: 0.5 },
  'corn': { sow: { week: 1, month: 'May' }, harvest: { week: 3, month: 'July' }, spacing: 1 },
  'asparagus': { sow: { week: 2, month: 'March' }, harvest: { week: 2, month: 'May' }, spacing: 1.5 },
  'artichoke': { startIndoors: { week: 1, month: 'February' }, transplant: { week: 2, month: 'April' }, harvest: { week: 3, month: 'June' }, spacing: 4 }
};